# paquete numpy

In [1]:
import numpy as np
import numpy.linalg as ln

## np.array

Con esto se pueden crear vectores, matrices y tensores.

In [2]:
vector=np.array([1,2,3,4])

matriz=np.array([[1,2],
                 [3,4]])

print(f"Vector:\n {vector}")
print("-"*100)
print(f"Matriz:\n {matriz}")


Vector:
 [1 2 3 4]
----------------------------------------------------------------------------------------------------
Matriz:
 [[1 2]
 [3 4]]


## $\text{np.shape}(a)$

### ¿ Que hace ?

Para saber el numero de filas y columnas de una matriz. Esto arroja una tupla.

### Parametros

$\bullet$ $a$ es el array.

In [3]:
matriz=np.array([[1,2,3],
                 [3,4,7]])

matriz.shape

(2, 3)

## $a\text{.zise}$

### ¿ Que hace ?

Para saber el numero de elementos de un array

### Parametros

$\bullet$ $a$ es el array

In [4]:
vector=np.array([1,2,3,4,5])

matriz=np.array([[1,2],
                 [3,4]])

print(f"Elementos vector:\n {vector.size}")
print("-"*100)
print(f"Elementos matriz:\n {matriz.size}")

Elementos vector:
 5
----------------------------------------------------------------------------------------------------
Elementos matriz:
 4


## $\text{np.zeros}(t)$

### ¿Que hace ?

Para crear el vector nulo o la matriz nula.

### Parametros

$\bullet$ $t$ es la tupla que define las filas y las colummnas del array.


In [5]:
vector_nulo=np.zeros(3)
matriz_nula=np.zeros((3,2))

print(f"Vector nulo:\n {vector_nulo}")
print("-"*100)
print(f"Matriz nula:\n {matriz_nula}")

Vector nulo:
 [0. 0. 0.]
----------------------------------------------------------------------------------------------------
Matriz nula:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


## $\text{np.ones}(t)$

### ¿ Que hace ?

Para crear un vector o una matriz solo de unos.

### Parametros

$\bullet$ $t$ es la tupla que define las filas y las colummnas del array.

In [6]:
vector=np.ones(3)
matriz=np.ones((3,2))

print(f"Vector de unos:\n {vector}")
print("-"*100)
print(f"Matriz de unos:\n {matriz}")

Vector de unos:
 [1. 1. 1.]
----------------------------------------------------------------------------------------------------
Matriz de unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


## $\text{np.arange}(a,b,c)$

### ¿ Que hace ?

Crea una secuencia en forma vector.

### Parametros

$\bullet$ $a$ y $b$ forman el valor inicial y final de la secuencia.

$\bullet$ $c$ es el número de terminos.

In [8]:
secuencia=np.arange(0,12,2)
print(f"Secuencia:\n {secuencia}")

Secuencia:
 [ 0  2  4  6  8 10]


## $\text{np.linespace}(a,b,c)$

### ¿ Que hace ?

Elejir términos de un intervalo.

### Parametros

$\bullet$ $a$ y $b$ forman el intervalo $[a,b]$ de donde se tomaran los términos.

$\bullet$ $c$ es el número de terminos.

In [9]:
puntos=np.linspace(-2,2,5)
print(f"Puntos:\n {puntos}")

Puntos:
 [-2. -1.  0.  1.  2.]


## $\text{np.logspace}(a_1,a_n,c)$

### ¿ Que hace ?

Crear una secuencia del tipo $10^n$.

### Parametros:

$\bullet$ $a_1$ y $a_n$ forman el conjunto $\{a_1 < a_2<\dots < a_n\}$ de exponentes donde $a_i\in\mathbb{N}$

$\bullet$ $c$ es el número de términos de la forma $10^n$.

In [11]:
secuencia=np.logspace(0,10,5)
print(f"Secuencia logaritmica:\n {secuencia}")

Secuencia logaritmica:
 [1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]


## $\text{np.meshgrid}(x,y)$

### ¿ Que hace ?

Crea dos matrices a partir de dos vectores, la cual sirve para evaluar funciones de dos variables y crear graficas 3D.

### Parametros:

$\bullet$ $x,y$ son los array.

In [14]:
x=np.array([1,2,12,-2])
y=np.array([1,-6,8,0])

X,Y=np.meshgrid(x,y)

print(f"X:\n {X}")
print("-"*100)
print(f"Y:\n {Y}")
print("-"*100)

# Donde Z[i,j] = X[i,j]**2 + Y[i,j]**2
Z=X**2+Y**2
print(f"Z:\n {Z}")


X:
 [[ 1  2 12 -2]
 [ 1  2 12 -2]
 [ 1  2 12 -2]
 [ 1  2 12 -2]]
----------------------------------------------------------------------------------------------------
Y:
 [[ 1  1  1  1]
 [-6 -6 -6 -6]
 [ 8  8  8  8]
 [ 0  0  0  0]]
----------------------------------------------------------------------------------------------------
Z:
 [[  2   5 145   5]
 [ 37  40 180  40]
 [ 65  68 208  68]
 [  1   4 144   4]]


## $\text{np.fromfunction}(\text{ \text{lambda} , (n,m)})$

Para crear una matriz donde cada entrada corresponde a un función $f(i,j)$, donde $i,j$ es la fila y columna de la matriz.

Se define la función y luego se da el tamaño de la matriz.

In [17]:
matriz=np.fromfunction(lambda i,j: i*j, (4,5))

print(f"Matriz:\n {matriz}")

Matriz:
 [[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  2.  4.  6.  8.]
 [ 0.  3.  6.  9. 12.]]


## $\text{np.reshape}(a,b)$

### ¿ Que hace?

Modificar el numero de filas o columnas de vector y una matriz.

### Parametros:

$\bullet$ $a$ y $b$ son el número de filas y columnas que se desean.


In [18]:
matriz=np.array([[1,2,3],
                 [4,5,6]])

matriz_a_dos_columnas=matriz.reshape(3,2)
matriz_a_una_fila=matriz.reshape(6)

print(f"Matriz a dos columnas:\n {matriz_a_dos_columnas}")
print("-"*100)
print(f"Matriz a una fila:\n {matriz_a_una_fila}")

Matriz a dos columnas:
 [[1 2]
 [3 4]
 [5 6]]
----------------------------------------------------------------------------------------------------
Matriz a una fila:
 [1 2 3 4 5 6]


## $a\text{.flatten}$

### ¿ Que hace ?

Convertir una matriz en un vector.

### Parametros:

$\bullet$ $a$ es el array.

In [19]:
matriz=np.array([[1,2],
                 [3,4]])
matriz_a_vector=matriz.flatten()
print(f"Matriz a vector:\n {matriz_a_vector}")

Matriz a vector:
 [1 2 3 4]


## np.vstack

Usar vectores como filas de una matriz.

Unir matrices en una sola

In [22]:
fila_1=np.array([1,2,3])

fila_2=np.array([-4,-5,-6])

matriz_1=np.array([[-1,-4,-5],
                   [1,2,3]])

matriz_2=np.array([[11,27,-3],
                   [4,-5,6]])

matriz_con_vectores=np.vstack((fila_1,fila_2))

Matriz_con_matrices=np.vstack((matriz_1,matriz_2))

print(f"Matriz con vectores:\n {matriz_con_vectores}")
print("-"*100)
print(f"Matriz con matrices:\n {Matriz_con_matrices}")

Matriz con vectores:
 [[ 1  2  3]
 [-4 -5 -6]]
----------------------------------------------------------------------------------------------------
Matriz con matrices:
 [[-1 -4 -5]
 [ 1  2  3]
 [11 27 -3]
 [ 4 -5  6]]


## np.hstack

Unir vectores en uno solo

Unir matrices en una sola

In [23]:
vector_1=np.array([1,2,3])

vector_2=np.array([-4,-5,-6])

matriz_1=np.array([[-1,-4,-5],
                   [1,2,3]])

matriz_2=np.array([[11,27,-3],
                   [4,-5,6]])

matriz_con_vectores=np.hstack((vector_1,vector_2))

Matriz_con_matrices=np.hstack((matriz_1,matriz_2))

print(f"Matriz con vectores:\n {matriz_con_vectores}")
print("-"*100)
print(f"Matriz con matrices:\n {Matriz_con_matrices}")

Matriz con vectores:
 [ 1  2  3 -4 -5 -6]
----------------------------------------------------------------------------------------------------
Matriz con matrices:
 [[-1 -4 -5 11 27 -3]
 [ 1  2  3  4 -5  6]]


## np.append

Agregar elementos a vectores o matrices.

La primera entrada es el array, el segundo es el elemento a agregar y el tercero es la forma de agregar el elemento, donde solo se puede poner $\text{axis}=0$ o $\text{axis}=1$.

In [26]:
vector=np.array([1,2,3])
matriz=np.array([[1,2,3],
                [4,5,6]])

data1=np.array([15,25,35,45])
data2=np.array([[-1,-2,-3],
                [14,15,16]])

vector_data1=np.append(vector,data1)
matriz_data2=np.append(matriz,data2,axis=1)

print(f"Vector con data1:\n {vector_data1}")
print("-"*100)
print(f"Matriz con data2:\n {matriz_data2}")


Vector con data1:
 [ 1  2  3 15 25 35 45]
----------------------------------------------------------------------------------------------------
Matriz con data2:
 [[ 1  2  3 -1 -2 -3]
 [ 4  5  6 14 15 16]]


## Operaciones de matrices

Solo las entrada por entrada

In [28]:
matriz1=np.array([[-1,2,3],
                 [4,-5,0]])
matriz2=np.array([[1,8,-9],
                 [10,-11,12]])

matriz_suma=matriz1+matriz2
matriz_resta=matriz1-matriz2
matriz_producto=matriz1*matriz2 
matriz_division=matriz1/matriz2
Matriz_potencia=matriz1**2

print(f"Matriz suma:\n {matriz_suma}")
print("-"*100)
print(f"Matriz resta:\n {matriz_resta}")
print("-"*100)
print(f"Matriz producto:\n {matriz_producto}")
print("-"*100)
print(f"Matriz division:\n {matriz_division}")
print("-"*100)
print(f"Matriz potencia:\n {Matriz_potencia}")

Matriz suma:
 [[  0  10  -6]
 [ 14 -16  12]]
----------------------------------------------------------------------------------------------------
Matriz resta:
 [[ -2  -6  12]
 [ -6   6 -12]]
----------------------------------------------------------------------------------------------------
Matriz producto:
 [[ -1  16 -27]
 [ 40  55   0]]
----------------------------------------------------------------------------------------------------
Matriz division:
 [[-1.          0.25       -0.33333333]
 [ 0.4         0.45454545  0.        ]]
----------------------------------------------------------------------------------------------------
Matriz potencia:
 [[ 1  4  9]
 [16 25  0]]


## $\text{np.mean}(a)$

### ¿Que hace?

Saca el promedio de todas las entradas de un array.

### Parametros

$\bullet$ $a$ es el array.

In [32]:
matriz=np.array([[1,2],
                 [3,4]])
media=np.mean(matriz)
print(f"Media matriz:\n {media}")

Media matriz:
 2.5
